  - name: Update and upgrade apt packages
    apt:
      upgrade: dist
  
  - name: Ensure Maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present      

  - name: create boxfuse directory
    file:
      path: "{{ boxfuse_path }}"
      state: directory
      mode: 0755

  - name: downloading the repository from GitHub
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: "{{ boxfuse_path }}"

  - name: building WAR file in Maven
    shell: mvn --file "{{ boxfuse_path }}"/pom.xml package

  - name: copy artifact to prod machine
    synchronize:
      mode: pull      
      src: "{{ boxfuse_path }}"/target/hello-1.0.war
      dest: "{{ tomcat_path }}"/webapps/
    delegate_to: "{{ groups['prod'] }}"