  - name: Update and upgrade apt packages
    apt:
      upgrade: dist
  
  - name: Ensure Maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present      

  - name: create /tmp/boxfuse directory
    file:
      path: /tmp/boxfuse
      state: directory
      mode: 0755

  - name: downloading the repository from GitHub
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse

  - name: building WAR file in Maven
    shell: mvn --file /tmp/boxfuse/pom.xml package

  - name: copy artifact to prod machine
    synchronize:
      mode: pull      
      src: /tmp/boxfuse/target/hello-1.0.war
      dest: /opt/tomcat/webapps/
    delegate_to: {{ groups['prod'] }}